<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="cell_wall">

<xacro:property name="cell_height" value="1.2"/>
<!-- <xacro:property name="cell_width" value="0.96"/> -->
<xacro:property name="cell_thick" value="0.05"/>

    <xacro:macro name="cell_wall" params="prefix parent *origin cell_width">
        <joint name="${prefix}cell_origin_joint" type="fixed" >
            <xacro:insert_block name="origin" />
            <parent link="${parent}" />
            <child link="${prefix}platform" />
        </joint>

        <link name="${prefix}platform">
            <inertial>
                <origin xyz="${cell_width/2} ${cell_thick/2} ${cell_height/2}" rpy="0 0 0"/>
                <mass value="5.0"/>
                <inertia ixx="0.442358" ixy="0" ixz="0" iyy="0.166085" iyz="0" izz="0.425124" />
            </inertial>
            <visual>
                <origin xyz="${cell_width/2} ${cell_thick/2} ${cell_height/2}" rpy="0 0 0"/>
                <geometry>
                    <!-- <mesh filename="package://ur5e_robotiq_gazebo/meshes/glass1.dae"/> -->
					<box size="${cell_width} ${cell_thick} ${cell_height}" />
                </geometry>
                <!-- <transparency>0.1</transparency> -->
                <material name="greyish">
                    <color rgba="0.8 0.8 0.8 0.1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="${cell_width/2} ${cell_thick/2} ${cell_height/2}" rpy="0 0 0" />
                <geometry>
                     <!-- <mesh filename="package://ur5e_robotiq_gazebo/meshes/glass1.dae"/> -->
					<box size="${cell_width} ${cell_thick} ${cell_height}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>

</robot>